### ISSUE TITLE
Pre-flight checklist

### ISSUE THREAD

**Issue by smithWEBtek** [MAPC/digitalhub#413]
Outline tasks that are needed for this release.
### Backup data
- [ ] Backup production database with `pg_dump`
- [ ] Adopt a storage and naming convention for backed up data.
- [ ] Run validations rake task in hubadmin | taggings page
- [ ] Communicate with external departments if needed based on validations check

### Update `site bar menu items`
- [ ] Edit the jquery in `app/views/refinery/_site_bar_menu.html` if needed to get specific URL's in the `site bar menu`.
- [ ] In hubadmin | pages | goals | advanced options, leave forwarding url box blank, so Rails can route `/goals`
- [ ] Uncheck `show in menu` option in hubadmin for 'Search' page
- [ ] Uncheck `show in menu` option in hubadmin for 'Tags' extension
- [ ] Uncheck `show in menu` option in hubadmin for 'Taggings' extension

**Comment by theryankelly** [comment]
Users need to have extensions (Plugin) access granted.
![Screen Shot 2019-09-04 at 10 59 35 AM](https://user-images.githubusercontent.com/2421382/64266755-25f25200-cf03-11e9-9bfa-ca90032083c3.png)
