### ISSUE TITLE
Decision: Confirm AA Landing Page Design

### ISSUE THREAD

**Issue by theryankelly** [MAPC/digitalhub#565]
These AA landing page templates will affect all 5 of these action areas"landing" pages.

Items to be confirmed:
- [x] Recomendation page link format **Boxes image in bg, full color on hover**
- [x] Vision statement location **In header, below menu**
- [x] Removal or location of introductory statement **Removed**
- [ ] Images for AA #559
- [ ] Images for AA Recomendations #585
- [ ] Related Goal Tagging #556 in sidebar?
- [x] Include option for pdf version download **Yes, we have this content and should make available**
- [x] Create specific Constant Contact list for each AA? **No, will use one link #573** but have button on each AA
- [x] Highlight actions in sidebar? **No, not including action cross links**
- [ ] #619

**Comment by theryankelly** [comment]
The first two AA landing pages to be experimented with in XD are #563 and #534.

**Comment by theryankelly** [comment]
Here is Equity of Wealth and Health #563 . These are examples for how the  Recommendation page link could be navigated to from this landing page:

## With boxes one for each
![image](https://user-images.githubusercontent.com/2421382/135338804-a2aff86c-adec-4dca-bfae-080c0af52245.png)

## With no boxes, mirroring header of recommendation page, strategies listed
![image](https://user-images.githubusercontent.com/2421382/135338960-b357433f-7270-4c30-87e1-fdd51d776b56.png)

## With wide boxes and strategies listed
![image](https://user-images.githubusercontent.com/2421382/135339108-9ff56831-cad5-4bc4-afa8-1405113ef40a.png)

Link to review: https://xd.adobe.com/view/59ab29a4-ad92-4fa4-862c-1f4bb4dbba01-0cf8/

**Comment by theryankelly** [comment]
I do have concerns about the contrast between text and all the AA colors. Upped the transparency from 75 to 80.

- [ ] Need to test accessibility of colors

![image](https://user-images.githubusercontent.com/2421382/135341856-88c79b90-a180-4312-bd70-aa49472d216e.png)

**Comment by theryankelly** [comment]
Adjust metadata section by removing from nav component

**Comment by theryankelly** [comment]
Closing this issue as remaining tasks all have their own issue
